[build]
  command = "npm run build"
  publish = "build"
  functions = "functions"

[template.environment]
  GITHUB_API_TOKEN = "Your Github Personal access token with repo/deploy scope"
  NETLIFY_API_TOKEN= "Your Netlify Personal access token"
  NETLIFY_OAUTH_CLIENT_ID = "Your Netlify OAuth Client ID"
  NETLIFY_OAUTH_CLIENT_SECRET= "Your Netlify OAuth Client Secret"
  NETLIFY_DEPLOY_KEY_ID="Generate with repo-connect function"